/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Shoppe example
 * The shop API description
 * OpenAPI spec version: 1.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateUserDTO,
  LoginUserDTO
} from '.././model';




  export const getAuth = () => {
const authControllerGet = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:3001/api/v1/auth`,options
    );
  }
const authControllerRefreshAcessToken = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:3001/api/v1/auth/refreshAT`,options
    );
  }
const authControllerCreate = <TData = AxiosResponse<void>>(
    createUserDTO: CreateUserDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:3001/api/v1/auth/signup`,
      createUserDTO,options
    );
  }
const authControllerLogin = <TData = AxiosResponse<void>>(
    loginUserDTO: LoginUserDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:3001/api/v1/auth/login`,
      loginUserDTO,options
    );
  }
const authControllerLogout = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `http://localhost:3001/api/v1/auth/logout`,undefined,options
    );
  }
return {authControllerGet,authControllerRefreshAcessToken,authControllerCreate,authControllerLogin,authControllerLogout}};
export type AuthControllerGetResult = AxiosResponse<void>
export type AuthControllerRefreshAcessTokenResult = AxiosResponse<void>
export type AuthControllerCreateResult = AxiosResponse<void>
export type AuthControllerLoginResult = AxiosResponse<void>
export type AuthControllerLogoutResult = AxiosResponse<void>
