/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Shoppe example
 * The shop API description
 * OpenAPI spec version: 1.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateCategoryDto,
  UpdateCategoryDto
} from '.././model';




  export const getCategory = () => {
const categoryControllerCreate = <TData = AxiosResponse<void>>(
    createCategoryDto: CreateCategoryDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:3001/api/v1/category`,
      createCategoryDto,options
    );
  }
const categoryControllerGetList = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:3001/api/v1/category`,options
    );
  }
const categoryControllerGetAll = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:3001/api/v1/category/all`,options
    );
  }
const categoryControllerFindOne = <TData = AxiosResponse<void>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:3001/api/v1/category/${id}`,options
    );
  }
const categoryControllerUpdate = <TData = AxiosResponse<void>>(
    id: number,
    updateCategoryDto: UpdateCategoryDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `http://localhost:3001/api/v1/category/${id}`,
      updateCategoryDto,options
    );
  }
const categoryControllerDelete = <TData = AxiosResponse<void>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `http://localhost:3001/api/v1/category/${id}`,options
    );
  }
return {categoryControllerCreate,categoryControllerGetList,categoryControllerGetAll,categoryControllerFindOne,categoryControllerUpdate,categoryControllerDelete}};
export type CategoryControllerCreateResult = AxiosResponse<void>
export type CategoryControllerGetListResult = AxiosResponse<void>
export type CategoryControllerGetAllResult = AxiosResponse<void>
export type CategoryControllerFindOneResult = AxiosResponse<void>
export type CategoryControllerUpdateResult = AxiosResponse<void>
export type CategoryControllerDeleteResult = AxiosResponse<void>
