/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Shoppe example
 * The shop API description
 * OpenAPI spec version: 1.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';




  export const getUser = () => {
const userControllerFindAll = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:3001/api/v1/users`,options
    );
  }
const userControllerFindOneById = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:3001/api/v1/users/${id}`,options
    );
  }
const userControllerDelete = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `http://localhost:3001/api/v1/users/${id}`,options
    );
  }
return {userControllerFindAll,userControllerFindOneById,userControllerDelete}};
export type UserControllerFindAllResult = AxiosResponse<void>
export type UserControllerFindOneByIdResult = AxiosResponse<void>
export type UserControllerDeleteResult = AxiosResponse<void>
