/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Shoppe example
 * The shop API description
 * OpenAPI spec version: 1.0
 */
import { api } from '../../../../lib/api';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getApp = () => {
  const appControllerPostST = (options?: SecondParameter<typeof api>) => {
    return api<void>(
      { url: `http://localhost:3001/api/v1/ok`, method: 'POST' },
      options,
    );
  };
  return { appControllerPostST };
};
export type AppControllerPostSTResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getApp>['appControllerPostST']>>
>;
