/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Shoppe example
 * The shop API description
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const uploadControllerUploadImageBody = zod.object({
  file: zod.instanceof(File),
});

export const uploadControllerUploadImageResponse = zod
  .object({
    success: zod.boolean(),
    statusCode: zod.number(),
    data: zod.object({}),
  })
  .and(
    zod.object({
      data: zod.string().optional(),
    }),
  );
