/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Shoppe example
 * The shop API description
 * OpenAPI spec version: 1.0
 */

export * from './apiResponse';
export * from './apiResponseResult';
export * from './createCategoryDto';
export * from './createUserDTO';
export * from './loginUserDTO';
export * from './product';
export * from './productControllerCreateProduct200';
export * from './productControllerCreateProduct200AllOf';
export * from './productControllerGetAllProduct200';
export * from './productControllerGetAllProduct200AllOf';
export * from './productControllerGetProductById200';
export * from './productControllerGetProductById200AllOf';
export * from './productControllerGetProductPagination200';
export * from './productControllerGetProductPagination200AllOf';
export * from './productControllerGetProductPaginationParams';
export * from './productControllerRemoveProduct200';
export * from './productControllerRemoveProduct200AllOf';
export * from './productControllerSearchProductByName200';
export * from './productControllerSearchProductByName200AllOf';
export * from './productControllerSearchProductByNameParams';
export * from './productControllerUpdateProductDetail200';
export * from './productControllerUpdateProductDetail200AllOf';
export * from './productPagingResponse';
export * from './productPagingResponsePagination';
export * from './productRequest';
export * from './productResponse';
export * from './updateCategoryDto';