/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Shoppe example
 * The shop API description
 * OpenAPI spec version: 1.0
 */
import type { ApiResponse } from './apiResponse';
import type { ProductControllerRemoveProduct200AllOf } from './productControllerRemoveProduct200AllOf';

export type ProductControllerRemoveProduct200 = ApiResponse & ProductControllerRemoveProduct200AllOf;
