/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Shoppe example
 * The shop API description
 * OpenAPI spec version: 1.0
 */
import type { ApiResponse } from './apiResponse';
import type { ProductControllerSearchProductByName200AllOf } from './productControllerSearchProductByName200AllOf';

export type ProductControllerSearchProductByName200 = ApiResponse & ProductControllerSearchProductByName200AllOf;
