/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Shoppe example
 * The shop API description
 * OpenAPI spec version: 1.0
 */

export interface ProductRequest {
  /** Product name */
  name: string;
  /** Product description */
  description: string;
  /** Product stock */
  stock: number;
  /** Product price */
  price: number;
  /** Product discount */
  discount: number;
  /** Product image */
  image: string;
  /** category id */
  categoryId: number;
}
