/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Shoppe example
 * The shop API description
 * OpenAPI spec version: 1.0
 */
import type { ApiResponse } from './apiResponse';
import type { ProductControllerUpdateProductDetail200AllOf } from './productControllerUpdateProductDetail200AllOf';

export type ProductControllerUpdateProductDetail200 = ApiResponse & ProductControllerUpdateProductDetail200AllOf;
