/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Shoppe example
 * The shop API description
 * OpenAPI spec version: 1.0
 */
import type { Product } from './product';

export type ProductControllerGetAllProduct200AllOf = {
  result?: Product[];
};
