/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Shoppe example
 * The shop API description
 * OpenAPI spec version: 1.0
 */

export interface ProductResponse {
  /** Product name */
  name: string;
  /** Product stock */
  stock: number;
  /** Product price */
  price: number;
  /** Product discount */
  discount: number;
  /** Product image */
  image: string;
  priceAfterDis: number;
  categoryName: string;
}
