/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Shoppe example
 * The shop API description
 * OpenAPI spec version: 1.0
 */
import type { APIResponseDTOData } from './aPIResponseDTOData';

export interface APIResponseDTO {
  success: boolean;
  statusCode: number;
  data: APIResponseDTOData;
}
