/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Shoppe example
 * The shop API description
 * OpenAPI spec version: 1.0
 */
import type { APIResponseDTO } from './aPIResponseDTO';
import type { CategoryControllerFindOne200AllOf } from './categoryControllerFindOne200AllOf';

export type CategoryControllerFindOne200 = APIResponseDTO &
  CategoryControllerFindOne200AllOf;
