/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Shoppe example
 * The shop API description
 * OpenAPI spec version: 1.0
 */
import type { Category } from './category';

export type CategoryControllerUpdate200AllOf = {
  data?: Category;
};
