/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Shoppe example
 * The shop API description
 * OpenAPI spec version: 1.0
 */
import type { APIResponseDTO } from './aPIResponseDTO';
import type { CategoryControllerCreate201AllOf } from './categoryControllerCreate201AllOf';

export type CategoryControllerCreate201 = APIResponseDTO &
  CategoryControllerCreate201AllOf;
