/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Shoppe example
 * The shop API description
 * OpenAPI spec version: 1.0
 */
import type { CategoryControllerGetListOrder } from './categoryControllerGetListOrder';

export type CategoryControllerGetListParams = {
  search?: string;
  sortBy?: string;
  order?: CategoryControllerGetListOrder;
  page?: number;
  pageSize?: number;
};
