/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Shoppe example
 * The shop API description
 * OpenAPI spec version: 1.0
 */
import type { APIResponseDTO } from './aPIResponseDTO';
import type { CategoryControllerDelete200AllOf } from './categoryControllerDelete200AllOf';

export type CategoryControllerDelete200 = APIResponseDTO &
  CategoryControllerDelete200AllOf;
