/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Shoppe example
 * The shop API description
 * OpenAPI spec version: 1.0
 */
import type { APIResponseDTO } from './aPIResponseDTO';
import type { CategoryControllerGetAll200AllOf } from './categoryControllerGetAll200AllOf';

export type CategoryControllerGetAll200 = APIResponseDTO &
  CategoryControllerGetAll200AllOf;
