/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Shoppe example
 * The shop API description
 * OpenAPI spec version: 1.0
 */

export interface Category {
  id: number;
  name: string;
  description: string;
  deleted: boolean;
  createdAt: string;
  updatedAt: string;
}
