/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Shoppe example
 * The shop API description
 * OpenAPI spec version: 1.0
 */
import type { APIResponseDTO } from './aPIResponseDTO';
import type { CategoryControllerUpdate200AllOf } from './categoryControllerUpdate200AllOf';

export type CategoryControllerUpdate200 = APIResponseDTO &
  CategoryControllerUpdate200AllOf;
