/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Shoppe example
 * The shop API description
 * OpenAPI spec version: 1.0
 */

export type CategoryControllerGetListOrder =
  (typeof CategoryControllerGetListOrder)[keyof typeof CategoryControllerGetListOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CategoryControllerGetListOrder = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const;
