/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Shoppe example
 * The shop API description
 * OpenAPI spec version: 1.0
 */

export interface ProductRequest {
  /**
   * Product name (e.g., CPU, GPU, RAM, etc.)
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /**
   * Short product description
   * @minLength 1
   * @maxLength 255
   */
  description: string;
  /**
   * Stock quantity available
   * @minimum 0
   */
  stock: number;
  /**
   * Product price in USD
   * @minimum 0
   */
  price: number;
  /**
   * Discount percentage (0-100)
   * @minimum 0
   * @maximum 100
   */
  discount: number;
  /**
   * URL of product image
   */
  image: string;
  /**
   * category id
   */
  categoryId: number;
}
