/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Shoppe example
 * The shop API description
 * OpenAPI spec version: 1.0
 */

export type ProductControllerGetProductPaginationParams = {
  text: string;
  page?: number;
  orderField?: string;
  orderBy?: string;
};
