/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Shoppe example
 * The shop API description
 * OpenAPI spec version: 1.0
 */

export interface ProductResponse {
  /** Product ID */
  id: number;
  /**
   * Product name (e.g., CPU, GPU, RAM, etc.)
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /**
   * Short product description
   * @minLength 1
   * @maxLength 255
   */
  description: string;
  /**
   * Stock quantity available
   * @minimum 0
   */
  stock: number;
  /**
   * Product price in USD
   * @minimum 0
   */
  price: number;
  /**
   * Discount percentage (0-100)
   * @minimum 0
   * @maximum 100
   */
  discount: number;
  /**
   * Average customer rating (0.0 - 5.0)
   * @minimum 0
   * @maximum 5
   * @nullable
   */
  rating: number | null;
  /**
   * URL of product image
   */
  image: string;
  /** Creation timestamp */
  createdAt: string;
  priceAfterDis: number;
  categoryName: string;
}
