/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Shoppe example
 * The shop API description
 * OpenAPI spec version: 1.0
 */
import type { ApiResponse } from './apiResponse';
import type { ProductControllerGetProductPagination200AllOf } from './productControllerGetProductPagination200AllOf';

export type ProductControllerGetProductPagination200 = ApiResponse &
  ProductControllerGetProductPagination200AllOf;
