/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Shoppe example
 * The shop API description
 * OpenAPI spec version: 1.0
 */
import type { APIResponseDTO } from './aPIResponseDTO';
import type { UploadControllerUploadImage200AllOf } from './uploadControllerUploadImage200AllOf';

export type UploadControllerUploadImage200 = APIResponseDTO &
  UploadControllerUploadImage200AllOf;
