/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Shoppe example
 * The shop API description
 * OpenAPI spec version: 1.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';




  export const getApp = () => {
const appControllerPostST = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:3001/api/v1/ok`,undefined,options
    );
  }
return {appControllerPostST}};
export type AppControllerPostSTResult = AxiosResponse<void>
